/**
 * HelpContent.jsx
 * Created by Mike Bray 4/1/16
 */

import React, { PropTypes } from 'react';
import $ from 'jquery';

const propTypes = {
    section: PropTypes.string,
    helpOnly: PropTypes.bool
};

const defaultProps = {
    section: '',
    helpOnly: false
};

export default class HelpContent extends React.Component {
    componentDidUpdate() {
        this.scrollToSection();
    }

    scrollToSection() {
        if (this.props.section && $(`[name=${this.props.section}]`).length > 0) {
            $('html, body').animate({
                scrollTop: $(`[name=${this.props.section}]`).offset().top
            }, 500);
        }
    }

    render() {
        let membership = null;
        if (this.props.helpOnly) {
            membership = (
                <div>
                    <h4 name="agencyAccess">Request Agency Access</h4>
                    <p>
                        The DATA Act Broker leverages MAX.gov for user accounts and password authentication.
                        To request a Broker account, you will first need a MAX.gov account.
                        If you do not have a MAX.gov account, you may register for one
                        <a
                            href="https://max.gov/maxportal/registrationForm.action"
                            rel="noopener noreferrer"
                            target="_blank">
                            here
                        </a>.
                    </p>
                    <p>
                        Once you have a MAX.gov account, navigate
                        <a href="https://community.max.gov/x/fJwuRQ" rel="noopener noreferrer" target="_blank">
                            here
                        </a>
                        , and follow the directions on
                        the page to request access to the DATA Act Broker through your agency.
                    </p>
                    <p>
                        If you have questions about Broker access, or if your agency is not listed on the MAX page
                        linked above, email
                        <a
                            href="mailto:DATAPMO@fiscal.treasury.gov?subject=Broker%20Access%20Information"
                            target="_top">
                            DATAPMO@fiscal.treasury.gov
                        </a>.
                    </p>
                </div>
            );
        }
        else {
            membership = (
                <p name="membership">
                    If you encounter a bug, have a question, or need help,
                    please register for the
                    <a href="https://servicedesk.usaspending.gov" rel="noopener noreferrer" target="_blank">
                        USAspending Service Desk
                    </a> and submit a ticket.
                    We can better resolve your issue if you provide us as much information as possible,
                    including the exact steps we should follow to replicate your issue and the page where you
                    encountered it. The Service Desk will email you if more information or clarification is needed.
                </p>
            );
        }

        return (
            <div className="usa-da-help-content">

                <h2 className="usa-da-help-content__header">What&#8217;s New in This Release</h2>
                <strong className="usa-da-help-content__date">February 7, 2019</strong>

                <p className="usa-da-help-content__content">In this release of the Broker, we:</p>
                <ul className="usa-da-help-content__list">
                    <li>Updated the Broker to implement the Federal Hierarchy validations and derivations described in DAIMS v1.3. Implemented a related one-time data enhancement that backfills office names from 10/1/2018 forward in FABS using provided office codes and the Federal Hierarchy.</li>
                    <li>Updated the Broker File A Generation in DABS to be based on period rather than fiscal quarter (quarters can still be generated by selecting periods 03, 06, 09, and 12, so no functionality was lost).</li>
                    <li>Updated Help section of the Broker to streamline it and reduce redundancies between it and the Fiscal Service DAIMS page (https://fiscal.treasury.gov/data-transparency/) and the Broker.</li>
                    <li>Various API documentation and error message improvements.</li>
                    <li>Updated job file size limit and memory management to allow larger D1/D2 files to generate without issue.</li>
                    <li>Various minor updates and improvements (Updated DABS Submission calendar document, Updated links to relaunched Fiscal Service Website, updated duplicate publication check to catch additional edge-case, improved special character handling in filenames and carriage return handling within data cells).</li>
                </ul>

                <h2 className="usa-da-help-content__header">Technical Notes for this Release</h2>
                <strong className="usa-da-help-content__date">February 7, 2019</strong>

                <p className="usa-da-help-content__content">In this release, here is a list of technical changes that may require infrastructure or database updates, or represents additional functionality.</p>
                <ul className="usa-da-help-content__list">
                    <li>Script and database migrations to store federal hierarchy office codes.</li>
                    <li>Database migrations creating separate tables for certified DABS data.</li>
                    <li>Refactors and database migrations improving the file generation workflow.</li>
                    <li>Database migration updating job file size from Integer to Big Integer for larger files.</li>
                    <li>Enforce 1-minute timeout for generated downloads. </li>
                </ul>
                <h2 className="usa-da-help-content-subheading">Getting More Help</h2>

                {membership}

                <p>
                    If you need assistance using the Broker or if you would like to schedule a hands-on sandbox session
                    with Treasury staff, please email
                    <a href="mailto:DATAPMO@fiscal.treasury.gov"> DATAPMO@fiscal.treasury.gov</a>.
                </p>
            </div>
        );
    }
}

HelpContent.propTypes = propTypes;
HelpContent.defaultProps = defaultProps;
