language: node_js
dist: focal
node_js:
  # latest in each series
  - "20.18.2"
# Need a C++ compiler
addons:
  chrome: stable
cache:
  directories:
    - node_modules
before_install:
  - npm install eslint@9.26.0
script:
  - npm run dev
  - npm run audit
