language: node_js
dist: focal
node_js:
  # latest in each series
  - "20.18.2"
# Need a C++ compiler
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
cache:
  directories:
    - node_modules
before_install:
  - npm install eslint@8.32.0
script:
  - npm run dev
  - npm run travis
