language: node_js
node_js:
  # latest in each series
  - "10.15.3"
# Need a C++ compiler
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
script:
  - npm run dev
  - npm run travis
