language: node_js
node_js:
  # latest in each series
    - "6"
    - "5"
    - "4"
# Need a C++ compiler
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
install:
  - npm install
  - npm install -g gulp
before_script:
  - cp sampleGlobalConstants_local.js GlobalConstants_local.js
script:
  - gulp buildLocal
  - eslint src/js
