language: node_js
node_js:
  # latest in each series
  - "16.14.2"
# Need a C++ compiler
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
cache:
  directories:
    - node_modules
script:
  - npm run dev
  - npm run travis
