export const agencies = [
            "Senate (000)",
            "House of Representatives (000)",
            "Joint Items (000)",
            "Capitol Police (002)",
            "Office of Compliance (009)",
            "Congressional Budget Office (008)",
            "Architect of the Capitol (001)",
            "Botanic Garden (009)",
            "Library of Congress (003)",
            "Government Printing Office (004)",
            "Government Accountability Office (005)",
            "United States Tax Court (023)",
            "Legislative Branch Boards and Commissions (009)",
            "Legislative Branch Boards and Commissions (283)",
            "Judicial Branch (010)",
            "Supreme Court of the United States (010)",
            "United States Court of Appeals for the Federal Circuit (010)",
            "United States Court of International Trade (010)",
            "Courts of Appeals, District Courts, and other Judicial Services (010)",
            "Administrative Office of the United States Courts (010)",
            "Federal Judicial Center (010)",
            "Judicial Retirement Funds (010)",
            "United States Sentencing Commission (010)",
            "Department of Agriculture - Department of Agriculture (012)",
            "Department of Agriculture - Office of the Secretary (012)",
            "Department of Agriculture - Executive Operations (012)",
            "Department of Agriculture - Office of Chief Economist (012)",
            "Department of Agriculture - National Appeals Division (012)",
            "Department of Agriculture - Office of Civil Rights (012)",
            "Department of Agriculture - Departmental Management (012)",
            "Department of Agriculture - Office of Communications (012)",
            "Department of Agriculture - Office of Inspector General (012)",
            "Department of Agriculture - Office of the General Counsel (012)",
            "Department of Agriculture - Economic Research Service (012)",
            "Department of Agriculture - National Agricultural Statistics Service (012)",
            "Department of Agriculture - Agricultural Research Service (012)",
            "Department of Agriculture - National Institute of Food and Agriculture (012)",
            "Department of Agriculture - Animal and Plant Health Inspection Service (012)",
            "Department of Agriculture - Food Safety and Inspection Service (012)",
            "Department of Agriculture - Grain Inspection, Packers and Stockyards Administration (012)",
            "Department of Agriculture - Agricultural Marketing Service (012)",
            "Department of Agriculture - Risk Management Agency (012)",
            "Department of Agriculture - Farm Service Agency (012)",
            "Department of Agriculture - Natural Resources Conservation Service (012)",
            "Department of Agriculture - Rural Development (012)",
            "Department of Agriculture - Rural Housing Service (012)",
            "Department of Agriculture - Rural Businessâ€”Cooperative Service (012)",
            "Department of Agriculture - Rural Utilities Service (012)",
            "Department of Agriculture - Foreign Agricultural Service (012)",
            "Department of Agriculture - Food and Nutrition Service (012)",
            "Department of Agriculture - Forest Service (012)",
            "Department of Commerce - Department of Commerce (013)",
            "Department of Commerce - Departmental Management (013)",
            "Department of Commerce - Economic Development Administration (013)",
            "Department of Commerce - Bureau of the Census (013)",
            "Department of Commerce - Economics and Statistics Administration (013)",
            "Department of Commerce - International Trade Administration (013)",
            "Department of Commerce - Bureau of Industry and Security (013)",
            "Department of Commerce - Minority Business Development Agency (013)",
            "Department of Commerce - National Oceanic and Atmospheric Administration (013)",
            "Department of Commerce - US Patent and Trademark Office (013)",
            "Department of Commerce - National Technical Information Service (013)",
            "Department of Commerce - National Institute of Standards and Technology (013)",
            "Department of Commerce - National Telecommunications and Information Administration (013)",
            "Department of Defense - Military Programs - Department of Defense - Military Programs",
            "Department of Defense - Military Programs - Military Personnel",
            "Department of Defense - Military Programs - Operation and Maintenance",
            "Department of Defense - Military Programs - International Reconstruction and Other Assistance",
            "Department of Defense - Military Programs - Procurement",
            "Department of Defense - Military Programs - Research, Development, Test, and Evaluation",
            "Department of Defense - Military Programs - Military Construction",
            "Department of Defense - Military Programs - Family Housing",
            "Department of Defense - Military Programs - Revolving and Management Funds",
            "Department of Defense - Military Programs - Allowances",
            "Department of Defense - Military Programs - Trust Funds",
            "Department of Education - Department of Education (091)",
            "Department of Education - Office of Elementary and Secondary Education (091)",
            "Department of Education - Office of Innovation and Improvement (091)",
            "Department of Education - Office of English Language Acquisition (091)",
            "Department of Education - Office of Special Education and Rehabilitative Services (091)",
            "Department of Education - Office of Vocational and Adult Education (091)",
            "Department of Education - Office of Postsecondary Education (091)",
            "Department of Education - Office of Federal Student Aid (091)",
            "Department of Education - Institute of Education Sciences (091)",
            "Department of Education - Departmental Management (091)",
            "Department of Education - Hurricane Education Recovery (091)",
            "Department of Energy - Department of Energy (089)",
            "Department of Energy - National Nuclear Security Administration (089)",
            "Department of Energy - Environmental and Other Defense Activities (089)",
            "Department of Energy - Energy Programs (089)",
            "Department of Energy - Power Marketing Administration (089)",
            "Department of Energy - Departmental Administration (089)",
            "Department of Health and Human Services - Department of Health and Human Services (075)",
            "Department of Health and Human Services - Food and Drug Administration (075)",
            "Department of Health and Human Services - Health Resources and Services Administration (075)",
            "Department of Health and Human Services - Indian Health Service (075)",
            "Department of Health and Human Services - Centers for Disease Control and Prevention (075)",
            "Department of Health and Human Services - National Institutes of Health (075)",
            "Department of Health and Human Services - Substance Abuse and Mental Health Services Administration (075)",
            "Department of Health and Human Services - Agency for Healthcare Research and Quality (075)",
            "Department of Health and Human Services - Centers for Medicare and Medicaid Services (075)",
            "Department of Health and Human Services - Administration for Children and Families (075)",
            "Department of Health and Human Services - Administration for Community Living (075)",
            "Department of Health and Human Services - Departmental Management (075)",
            "Department of Health and Human Services - Program Support Center (075)",
            "Department of Health and Human Services - Office of the Inspector General (075)",
            "Department of Homeland Security - Department of Homeland Security (070)",
            "Department of Homeland Security - Departmental Management and Operations (070)",
            "Department of Homeland Security - Office of the Inspector General (070)",
            "Department of Homeland Security - Citizenship and Immigration Services (070)",
            "Department of Homeland Security - United States Secret Service (070)",
            "Department of Homeland Security - Transportation Security Administration (070)",
            "Department of Homeland Security - Federal Law Enforcement Training Center (070)",
            "Department of Homeland Security - Immigration and Customs Enforcement (070)",
            "Department of Homeland Security - Customs and Border Protection (070)",
            "Department of Homeland Security - United States Coast Guard (070)",
            "Department of Homeland Security - National Protection and Programs Directorate (070)",
            "Department of Homeland Security - Federal Emergency Management Agency (070)",
            "Department of Homeland Security - Science and Technology (070)",
            "Department of Homeland Security - Domestic Nuclear Detection Office (070)",
            "Department of Homeland Security - Information Analysis and Infrastructure Protection (070)",
            "Department of Housing and Urban Development - Department of Housing and Urban Development (086)",
            "Department of Housing and Urban Development - Public and Indian Housing Programs (086)",
            "Department of Housing and Urban Development - Community Planning and Development (086)",
            "Department of Housing and Urban Development - Housing Programs (086)",
            "Department of Housing and Urban Development - Government National Mortgage Association (086)",
            "Department of Housing and Urban Development - Policy Development and Research (086)",
            "Department of Housing and Urban Development - Fair Housing and Equal Opportunity (086)",
            "Department of Housing and Urban Development - Office of Lead Hazard Control and Healthy Homes (086)",
            "Department of Housing and Urban Development - Office of Sustainable Housing and Communities (086)",
            "Department of Housing and Urban Development - Management and Administration (086)",
            "Department of the Interior - Department of the Interior (014)",
            "Department of the Interior - Bureau of Land Management (014)",
            "Department of the Interior - Bureau of Ocean Energy Management (014)",
            "Department of the Interior - Office of Surface Mining Reclamation and Enforcement (014)",
            "Department of the Interior - Bureau of Reclamation (014)",
            "Department of the Interior - Central Utah Project (014)",
            "Department of the Interior - United States Geological Survey (014)",
            "Department of the Interior - United States Fish and Wildlife Service (014)",
            "Department of the Interior - Bureau of Safety and Environmental Enforcement (014)",
            "Department of the Interior - National Park Service (014)",
            "Department of the Interior - Bureau of Indian Affairs and Bureau of Indian Education (014)",
            "Department of the Interior - Departmental Offices (014)",
            "Department of the Interior - Insular Affairs (014)",
            "Department of the Interior - Office of the Solicitor (014)",
            "Department of the Interior - Office of Inspector General (014)",
            "Department of the Interior - Office of the Special Trustee for American Indians (014)",
            "Department of the Interior - National Indian Gaming Commission (014)",
            "Department of the Interior - Department-Wide Programs (014)",
            "Department of Justice - Department of Justice (015)",
            "Department of Justice - General Administration (015)",
            "Department of Justice - United States Parole Commission (015)",
            "Department of Justice - Legal Activities and US Marshals (015)",
            "Department of Justice - National Security Division (015)",
            "Department of Justice - Radiation Exposure Compensation (015)",
            "Department of Justice - Interagency Law Enforcement (015)",
            "Department of Justice - Federal Bureau of Investigation (015)",
            "Department of Justice - Drug Enforcement Administration (015)",
            "Department of Justice - Bureau of Alcohol, Tobacco, Firearms, and Explosives (015)",
            "Department of Justice - Federal Prison System (015)",
            "Department of Justice - Office of Justice Programs (015)",
            "Department of Justice - Violent Crime Reduction Trust Fund (015)",
            "Department of Labor - Department of Labor (016)",
            "Department of Labor - Employment and Training Administration (016)",
            "Department of Labor - Employee Benefits Security Administration (016)",
            "Department of Labor - Pension Benefit Guaranty Corporation (016)",
            "Department of Labor - Employment Standards Administration (016)",
            "Department of Labor - Office of Workers' Compensation Programs (016)",
            "Department of Labor - Wage and Hour Division (016)",
            "Department of Labor - Office of Federal Contract Compliance Programs (016)",
            "Department of Labor - Office of Labor Management Standards (016)",
            "Department of Labor - Occupational Safety and Health Administration (016)",
            "Department of Labor - Mine Safety and Health Administration (016)",
            "Department of Labor - Bureau of Labor Statistics (016)",
            "Department of Labor - Departmental Management (016)",
            "Department of State - Department of State (019)",
            "Department of State - Administration of Foreign Affairs (019)",
            "Department of State - International Organizations and Conferences (019)",
            "Department of State - International Commissions (019)",
            "Department of State - Other (011)",
            "Department of State - Other (019)",
            "Department of State - Other (072)",
            "Department of State - Other (570)",
            "Department of Transportation - Department of Transportation (069)",
            "Department of Transportation - Office of the Secretary (069)",
            "Department of Transportation - Federal Aviation Administration (069)",
            "Department of Transportation - Federal Highway Administration (069)",
            "Department of Transportation - Federal Motor Carrier Safety Administration (069)",
            "Department of Transportation - National Highway Traffic Safety Administration (069)",
            "Department of Transportation - Federal Railroad Administration (069)",
            "Department of Transportation - Federal Transit Administration (069)",
            "Department of Transportation - Saint Lawrence Seaway Development Corporation (069)",
            "Department of Transportation - Pipeline and Hazardous Materials Safety Administration (069)",
            "Department of Transportation - Office of Inspector General (069)",
            "Department of Transportation - Surface Transportation Board (069)",
            "Department of Transportation - Maritime Administration (069)",
            "Department of the Treasury - Department of the Treasury (020)",
            "Department of the Treasury - Departmental Offices (020)",
            "Department of the Treasury - Financial Crimes Enforcement Network (020)",
            "Department of the Treasury - Fiscal Service (020)",
            "Department of the Treasury - Federal Financing Bank (020)",
            "Department of the Treasury - Alcohol and Tobacco Tax and Trade Bureau (020)",
            "Department of the Treasury - Bureau of Engraving and Printing (020)",
            "Department of the Treasury - United States Mint (020)",
            "Department of the Treasury - Internal Revenue Service (020)",
            "Department of the Treasury - Comptroller of the Currency (020)",
            "Department of the Treasury - Interest on the Public Debt (020)",
            "Department of Veterans Affairs - Department of Veterans Affairs (036)",
            "Department of Veterans Affairs - Veterans Health Administration (036)",
            "Department of Veterans Affairs - Benefits Programs (036)",
            "Department of Veterans Affairs - Departmental Administration (036)",
            "Other Defense Civil Programs - Other Defense Civil Programs",
            "Other Defense Civil Programs - Military Retirement (097)",
            "Other Defense Civil Programs - Retiree Health Care (097)",
            "Other Defense Civil Programs - Educational Benefits (097)",
            "Other Defense Civil Programs - American Battle Monuments Commission (074)",
            "Other Defense Civil Programs - Armed Forces Retirement Home (084)",
            "Other Defense Civil Programs - Cemeterial Expenses (021)",
            "Other Defense Civil Programs - Forest and Wildlife Conservation, Military Reservations (017)",
            "Other Defense Civil Programs - Selective Service System (090)",
            "International Assistance Programs - International Assistance Programs",
            "International Assistance Programs - Millennium Challenge Corporation (524)",
            "International Assistance Programs - International Security Assistance (072)",
            "International Assistance Programs - International Security Assistance (072)",
            "International Assistance Programs - Multilateral Assistance (011)",
            "International Assistance Programs - Multilateral Assistance (019)",
            "International Assistance Programs - Multilateral Assistance (072)",
            "International Assistance Programs - Agency for International Development (011)",
            "International Assistance Programs - Agency for International Development (072)",
            "International Assistance Programs - Overseas Private Investment Corporation (071)",
            "International Assistance Programs - Trade and Development Agency (011)",
            "International Assistance Programs - Peace Corps (011)",
            "International Assistance Programs - Inter-American Foundation (011)",
            "International Assistance Programs - African Development Foundation (011)",
            "International Assistance Programs - International Monetary Programs (011)",
            "International Assistance Programs - Military Sales Program (011)",
            "International Assistance Programs - Special Assistance Initiatives (072)",
            "International Assistance Programs - Foreign Assistance Program Allowances",
            "Executive Office of the President - Executive Office of the President (011)",
            "Executive Office of the President - The White House (011)",
            "Executive Office of the President - Executive Residence at the White House (011)",
            "Executive Office of the President - Special Assistance to the President and the Official Residence of the Vice President (011)",
            "Executive Office of the President - Council of Economic Advisers (011)",
            "Executive Office of the President - Council on Environmental Quality and Office of Environmental  Quality (011)",
            "Executive Office of the President",
            "Executive Office of the President - National Security Council and Homeland Security Council (011)",
            "Executive Office of the President - Office of Administration (011)",
            "Executive Office of the President - Office of Management and Budget (011)",
            "Executive Office of the President - Office of National Drug Control Policy (011)",
            "Executive Office of the President - Office of Science and Technology Policy (011)",
            "Executive Office of the President - Office of the United States Trade Representative (011)",
            "Executive Office of the President - Unanticipated Needs (011)",
            "Executive Office of the President - Presidential Transition (011)",
            "Corps of Engineers - Civil Works (096)",
            "Environmental Protection Agency (068)",
            "General Services Administration - General Services Administration (047)",
            "General Services Administration - Real Property Activities (047)",
            "General Services Administration - Supply and Technology Activities (047)",
            "General Services Administration - General Activities (047)",
            "National Aeronautics and Space Administration (080)",
            "National Science Foundation (049)",
            "Office of Personnel Management (024)",
            "Small Business Administration (073)",
            "Social Security Administration (028)",
            "Access Board (310)",
            "Administrative Conference of the United States (302)",
            "Advisory Council on Historic Preservation (306)",
            "Affordable Housing Program",
            "Appalachian Regional Commission (309)",
            "Barry Goldwater Scholarship and Excellence in Education Foundation (313)",
            "Broadcasting Board of Governors (514)",
            "Bureau of Consumer Financial Protection (581)",
            "Central Intelligence Agency (056)",
            "Chemical Safety and Hazard Investigation Board (510)",
            "Christopher Columbus Fellowship Foundation (465)",
            "Civilian Property Realignment Board",
            "Commission of Fine Arts (323)",
            "Commission on Civil Rights (326)",
            "Committee for Purchase from People who are Blind or Severely Disabled, activities (338)",
            "Commodity Futures Trading Commission (339)",
            "Consumer Product Safety Commission (061)",
            "Corporation for National and Community Service (485)",
            "Corporation for Public Broadcasting (020)",
            "Corporation for Travel Promotion (580)",
            "Council of the Inspectors General on Integrity and Efficiency (542)",
            "Court Services and Offender Supervision Agency for the District of Columbia (511)",
            "Defense Nuclear Facilities Safety Board (347)",
            "Delta Regional Authority (517)",
            "Denali Commission (513)",
            "District of Columbia - District of Columbia Courts (349)",
            "District of Columbia - District of Columbia General and Special Payments (020)",
            "Election Assistance Commission (525)",
            "Electric Reliability Organization",
            "Equal Employment Opportunity Commission (045)",
            "Export-Import Bank of the United States (083)",
            "Farm Credit Administration (352)",
            "Farm Credit System Insurance Corporation (352)",
            "Federal Communications Commission (027)",
            "Federal Deposit Insurance Corporation - Deposit Insurance (051)",
            "Federal Deposit Insurance Corporation - FSLIC Resolution (051)",
            "Federal Deposit Insurance Corporation - Orderly Liquidation (051)",
            "Federal Deposit Insurance Corporation - FDIC Office of Inspector General (051)",
            "Federal Drug Control Programs (011)",
            "Federal Election Commission (360)",
            "Federal Financial Institutions Examination Council (362)",
            "Federal Financial Institutions Examination Council Appraisal Subcommittee (362)",
            "Federal Housing Finance Agency (537)",
            "Federal Labor Relations Authority (054)",
            "Federal Maritime Commission (065)",
            "Federal Mediation and Conciliation Service (093)",
            "Federal Mine Safety and Health Review Commission (368)",
            "Federal Retirement Thrift Investment Board (026)",
            "Federal Trade Commission (029)",
            "Harry S Truman Scholarship Foundation (372)",
            "Independent Payment Advisory Board",
            "Indian Law and Order Commission (584)",
            "Institute of American Indian and Alaska Native Culture and Arts Development (373)",
            "Institute of Museum and Library Services (417)",
            "Intelligence Community Management Account (467)",
            "International Trade Commission (034)",
            "James Madison Memorial Fellowship Foundation (381)",
            "Japan-United States Friendship Commission (382)",
            "Legal Services Corporation (020)",
            "Marine Mammal Commission (387)",
            "Merit Systems Protection Board (389)",
            "Morris K Udall and Stewart L Udall Foundation (487)",
            "National Archives and Records Administration (088)",
            "National Capital Planning Commission (394)",
            "National Council on Disability (413)",
            "National Credit Union Administration (025)",
            "National Endowment for the Arts (417)",
            "National Endowment for the Humanities (417)",
            "National Infrastructure Bank",
            "National Labor Relations Board (420)",
            "National Mediation Board (421)",
            "National Railroad Passenger Corporation Office of Inspector General (575)",
            "National Transportation Safety Board (424)",
            "Neighborhood Reinvestment Corporation (082)",
            "Northern Border Regional Commission (573)",
            "Nuclear Regulatory Commission (031)",
            "Nuclear Waste Technical Review Board (431)",
            "Occupational Safety and Health Review Commission (432)",
            "Office of Government Ethics (434)",
            "Office of Navajo and Hopi Indian Relocation (435)",
            "Office of Special Counsel (062)",
            "Office of the Federal Coordinator for Alaska Natural Gas Transportation Projects (534)",
            "Other Commissions and Boards (382)",
            "Patient-Centered Outcomes Research Trust Fund (579)",
            "Postal Service (018)",
            "Presidio Trust (512)",
            "Privacy and Civil Liberties Oversight Board (535)",
            "Railroad Retirement Board (060)",
            "Recovery Act Accountability and Transparency Board (539)",
            "Securities and Exchange Commission (050)",
            "Public Company Accounting Oversight Board",
            "Standard Setting Body",
            "Securities Investor Protection Corporation",
            "Smithsonian Institution (033)",
            "State Justice Institute (453)",
            "Telecommunications Development Fund",
            "Tennessee Valley Authority (455)",
            "United Mine Workers of America Benefit Funds",
            "United States Court of Appeals for Veterans Claims (345)",
            "United States Enrichment Corporation Fund (486)",
            "United States Holocaust Memorial Museum (456)",
            "United States Institute of Peace (458)",
            "United States Interagency Council on Homelessness (376)",
            "Vietnam Education Foundation (519)",
            "Government Sponsored Enterprises",
            "Federal National Mortgage Association (915)",
            "Federal Home Loan Mortgage Corporation (914)",
            "Federal Home Loan Bank System (913)",
            "Farm Credit System (912)",
            "Financing Vehicles and the Board of Governors of the Federal Reserve (920"
        ];