export const agencies = [
            "Appalachian Regional Commission",
            "Broadcasting Board of Governors",
            "Bureau of Safety and Environmental Enforcement",
            "Commerce - Economic Development Administration",
            "Commerce - International Trade Administration",
            "Commerce - Minority Business Development Agency",
            "Commerce - National Institute of Standards and Technology",
            "Commerce - National Oceanic and Atmospheric Administration",
            "Commerce - Office of the Secretary",
            "Commission on Civil Rights",
            "Consumer Product Safety Commission",
            "Corporation for National and Community Service",
            "Defense Nuclear Facilities Safety Board",
            "Delta Regional Authority",
            "Denali Commission",
            "Department of Agriculture",
            "Department of Defense (except military departments)",
            "Department of Education",
            "Department of Energy",
            "Department of Health and Human Services",
            "Department of Homeland Security",
            "Department of Housing and Urban Development",
            "Department of Justice",
            "Department of Labor",
            "Department of State",
            "Department of the Interior ",
            "Department of the Treasury",
            "Department of Veterans Affairs",
            "DOT - Department of Transportation",
            "DOT - Federal Aviation Administration",
            "DOT - Federal Highway Administration",
            "DOT - Federal Motor Carrier Safety Administration",
            "DOT - Federal Railroad Administration",
            "DOT - Federal Transit Administration",
            "DOT - Immediate Office of the Secretary of Transportation",
            "DOT - Maritime Administration",
            "DOT - National Highway Traffic Safety Administration",
            "DOT - Pipeline and Hazardous Materials Safety Administration",
            "Election Assistance Commission",
            "Environmental Protection Agency",
            "Export-Import Bank of the U.S.",
            "Federal Communications Commission",
            "Federal Energy Regulatory Commission",
            "Federal Mediation and Conciliation Service",
            "Federal Trade Commission",
            "General Services Administration",
            "Gulf Coast Ecosystem Restoration Council",
            "Institute of Museum Services",
            "Inter-American Foundation",
            "Japan-U.S. Friendship Commission",
            "Millennium Challenge Corporation",
            "National Aeronautics and Space Administration",
            "National Archives and Records Administration",
            "National Credit Union Administration",
            "National Endowment for the Arts",
            "National Endowment for the Humanities",
            "National Labor Relations Board",
            "National Science Foundation",
            "Nuclear Regulatory Commission",
            "Office of Personnel Management",
            "Office of the National Drug Control Policy",
            "Open World Leadership Center",
            "Overseas Private Investment Corporation",
            "Pension Benefit Guaranty Corporation",
            "Railroad Retirement Board",
            "Small Business Administration",
            "Social Security Administration",
            "U.S. Agency for International Development",
            "U.S. Coast Guard",
            "United States Institute of Peace"
        ];