export default {
    children: {},
    dispatch: jest.fn(),
    history: {},
    item: {},
    location: {},
    params: {},
    removeUploadItem: jest.fn(),
    resetSubmission: jest.fn(),
    route: {},
    routeParams: {},
    routes: {},
    session: {},
    setCrossFile: jest.fn(),
    setCrossFileStage: jest.fn(),
    setExpectedCrossPairs: jest.fn(),
    setMeta: jest.fn(),
    setSubmissionId: jest.fn(),
    setSubmissionPublishStatus: jest.fn(),
    setSubmissionState: jest.fn(),
    setUploadItem: jest.fn(),
    setUploadProgress: jest.fn(),
    setUploadState: jest.fn(),
    setValidation: jest.fn(),
    submission: {}
};
